<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @mixin IdeHelperTeam
 */
class Team extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'owner_id',
        'slug'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // when team is created, add current user as team member
        static::created(function (Team $team) {
            $team->members()->attach((auth()->id()));
        });

        // when deleting team
        static::deleting(function (Team $team) {
            $team->members()->sync([]);
        });
    }

    public function owner(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'owner_id');
    }

    public function members(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function designs(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Design::class);
    }

    public function invitations(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Invitation::class);
    }

    public function hasPendingInvite(string $email): bool
    {
        return (bool)$this->invitations()->where('recipient_email', $email)->count();
    }

    public function hasUser(User $user): bool
    {
        return (bool)$this->members()->where('user_id', $user->id)->first();
    }
}
